name: Sync Fork with Upstream
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sync upstream
        uses: dabreadman/sync-upstream-repo@v1.0.0.b
        with:
          upstream_repo: "https://github.com/brave/adblock-rust.git"
          upstream_branch: main
          downstream_branch: main
          token: ${{ secrets.GITHUB_TOKEN }}   
